import React from "react";
import { Card, CardContent, CardHeader } from "./ui/card";
import { Badge } from "./ui/badge";
import { Separator } from "./ui/separator";
import {
  Building2,
  Mail,
  Phone,
  Globe,
  Calendar,
  CreditCard,
} from "lucide-react";

interface InvoiceTemplateProps {
  organization: {
    id: string;
    name: string;
    domain: string;
    plan: string;
    billingEmail: string;
    monthlyRevenue: number;
    users: number;
  };
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  adminName: string;
}

export function InvoiceTemplate({
  organization,
  invoiceNumber,
  issueDate,
  dueDate,
  adminName,
}: InvoiceTemplateProps) {
  const getPlanDetails = (plan: string) => {
    switch (plan) {
      case "starter":
        return {
          name: "Starter Plan",
          price: 999,
          features: [
            "Inventory Management",
            "GST-Compliant POS",
            "Basic Reports",
            "WhatsApp Alerts",
          ],
        };
      case "growth":
        return {
          name: "Growth Plan",
          price: 2999,
          features: [
            "Everything in Starter",
            "E-commerce Sync",
            "Smart Automation",
            "Multi-user Access",
          ],
        };
      case "pro":
        return {
          name: "Pro Plan",
          price: 9999,
          features: [
            "Everything in Growth",
            "AI Analytics",
            "MSME Consulting",
            "Priority Support",
          ],
        };
      case "enterprise":
        return {
          name: "Enterprise Plan",
          price: 25000,
          features: [
            "All Features",
            "Dedicated Support",
            "Custom Integrations",
            "SLA Guarantee",
          ],
        };
      default:
        return { name: "Unknown Plan", price: 0, features: [] };
    }
  };

  const planDetails = getPlanDetails(organization.plan);
  const subtotal = planDetails.price;
  const gstRate = 18; // 18% GST
  const gstAmount = Math.round((subtotal * gstRate) / 100);
  const total = subtotal + gstAmount;

  return (
    <div className="max-w-4xl mx-auto bg-white text-black p-8 print:shadow-none shadow-lg">
      {/* Header */}
      <div className="flex justify-between items-start mb-8">
        <div>
          <div className="flex items-center gap-3 mb-4">
            <div className="h-12 w-12 bg-blue-600 rounded-lg flex items-center justify-center">
              <Building2 className="h-7 w-7 text-white" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-blue-600">Uneora</h1>
              <p className="text-sm text-gray-600">
                Smart Inventory Management Platform
              </p>
            </div>
          </div>
          <div className="text-sm text-gray-600 space-y-1">
            <div className="flex items-center gap-2">
              <Building2 className="h-4 w-4" />
              <span>Builder.io Technologies Pvt Ltd</span>
            </div>
            <div className="flex items-center gap-2">
              <Mail className="h-4 w-4" />
              <span>billing@uneora.com</span>
            </div>
            <div className="flex items-center gap-2">
              <Phone className="h-4 w-4" />
              <span>+91 80-4567-8901</span>
            </div>
            <div className="flex items-center gap-2">
              <Globe className="h-4 w-4" />
              <span>www.uneora.com</span>
            </div>
          </div>
        </div>

        <div className="text-right">
          <h2 className="text-2xl font-bold text-gray-800 mb-2">INVOICE</h2>
          <div className="text-sm space-y-1">
            <div>
              <strong>Invoice #:</strong> {invoiceNumber}
            </div>
            <div>
              <strong>Issue Date:</strong>{" "}
              {new Date(issueDate).toLocaleDateString("en-IN")}
            </div>
            <div>
              <strong>Due Date:</strong>{" "}
              {new Date(dueDate).toLocaleDateString("en-IN")}
            </div>
            <div>
              <strong>Generated by:</strong> {adminName}
            </div>
          </div>
        </div>
      </div>

      <Separator className="my-6" />

      {/* Bill To */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        <div>
          <h3 className="text-lg font-semibold text-gray-800 mb-3">Bill To:</h3>
          <div className="space-y-2">
            <div className="font-medium text-lg">{organization.name}</div>
            <div className="text-gray-600">{organization.domain}</div>
            <div className="flex items-center gap-2 text-gray-600">
              <Mail className="h-4 w-4" />
              <span>{organization.billingEmail}</span>
            </div>
            <div className="text-sm text-gray-500">
              Organization ID: {organization.id}
            </div>
          </div>
        </div>

        <div>
          <h3 className="text-lg font-semibold text-gray-800 mb-3">
            Service Details:
          </h3>
          <div className="space-y-2 text-sm">
            <div>
              <strong>Current Plan:</strong> {planDetails.name}
            </div>
            <div>
              <strong>Active Users:</strong> {organization.users}
            </div>
            <div>
              <strong>Billing Period:</strong> Monthly
            </div>
            <div>
              <strong>Service Status:</strong>{" "}
              <Badge variant="default">Active</Badge>
            </div>
          </div>
        </div>
      </div>

      {/* Invoice Items */}
      <div className="mb-8">
        <h3 className="text-lg font-semibold text-gray-800 mb-4">
          Invoice Details
        </h3>
        <div className="border rounded-lg overflow-hidden">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left p-4 font-medium">Description</th>
                <th className="text-center p-4 font-medium">Period</th>
                <th className="text-right p-4 font-medium">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              <tr>
                <td className="p-4">
                  <div className="font-medium">
                    {planDetails.name} - Monthly Subscription
                  </div>
                  <div className="text-sm text-gray-600 mt-1">
                    Includes: {planDetails.features.slice(0, 2).join(", ")}
                    {planDetails.features.length > 2 &&
                      ` + ${planDetails.features.length - 2} more features`}
                  </div>
                </td>
                <td className="p-4 text-center text-sm text-gray-600">
                  {new Date(issueDate).toLocaleDateString("en-IN", {
                    month: "short",
                    year: "numeric",
                  })}
                </td>
                <td className="p-4 text-right font-medium">
                  ₹{subtotal.toLocaleString()}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Totals */}
      <div className="flex justify-end mb-8">
        <div className="w-80">
          <div className="space-y-2">
            <div className="flex justify-between">
              <span>Subtotal:</span>
              <span>₹{subtotal.toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span>GST ({gstRate}%):</span>
              <span>₹{gstAmount.toLocaleString()}</span>
            </div>
            <Separator />
            <div className="flex justify-between text-lg font-bold">
              <span>Total Amount:</span>
              <span>₹{total.toLocaleString()}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Payment Information */}
      <Card className="mb-6 border-blue-200 bg-blue-50">
        <CardHeader className="pb-3">
          <div className="flex items-center gap-2">
            <CreditCard className="h-5 w-5 text-blue-600" />
            <h3 className="font-semibold text-blue-800">Payment Information</h3>
          </div>
        </CardHeader>
        <CardContent className="text-sm text-blue-700 space-y-2">
          <div>
            <strong>Payment Methods:</strong> Razorpay, UPI, Bank Transfer,
            Credit/Debit Cards
          </div>
          <div>
            <strong>Payment Terms:</strong> Net 15 days from invoice date
          </div>
          <div>
            <strong>Late Payment:</strong> 2% per month on overdue amounts
          </div>
          <div>
            <strong>Support:</strong> Contact billing@uneora.com for payment
            queries
          </div>
        </CardContent>
      </Card>

      {/* Footer */}
      <div className="text-center text-sm text-gray-500 border-t pt-6">
        <p className="mb-2">
          Thank you for choosing Uneora for your inventory management needs!
        </p>
        <p>
          This is a system-generated invoice. For support, contact us at
          support@uneora.com
        </p>
        <p className="mt-2">
          <strong>GST Number:</strong> 29ABCDE1234F1Z5 | <strong>PAN:</strong>{" "}
          ABCDE1234F
        </p>
      </div>
    </div>
  );
}
